<?php
// upload file form POST process (from uploadFile.php, modal window)
require($_SERVER['DOCUMENT_ROOT'].'/_code/inc/first_include.php');
require(ROOT.'_code/admin/not_logged_in.php');
require(ROOT.'_code/admin/admin_functions.php');

// increase memory size to allow heavy image manipulations (rotating large image and generating sized-down copies)
ini_set('memory_limit','160M');

// upload file form process
if(isset($_POST['uploadFileSubmit'])){
    $path = urldecode($_POST['path']);
    $file_type = $_FILES['file']['type'];
	
	// get and format file extension
	if(isset($file_type) && !empty($file_type)){ // get it from file metadata
		$split = explode('/', $file_type);
		$ext = '.'.strtolower($split[1]);
		$ext = str_replace('jpeg', 'jpg', $ext);
		// Mac .txt files can use the "plain" file type (for plain text)!...
		if($ext == '.plain' || $ext == '.text'){
			$ext = '.txt';
		}
		// msword file type (can be generated by open office)... and docx can be .doc, to use the doc.png icon...
		if($ext == '.msword' || $ext == '.docx'){
			$ext = '.doc';
		}
	}else{ // if no metadata, take file extension
		$ext = file_extension($file_name);
		$ext = strtolower($ext);
		$ext = str_replace('jpeg', 'jpg', $ext);
    }
    
    $file_name = 'bg'.$ext;
    $dest = $path.$file_name;
	if( up_file($dest) ){
        $upload_result = 'file uploaded';
    }else{
        $upload_result = 'error';
    }
	header("location: ".$_SERVER['HTTP_REFERER']."?upload_result=".urlencode($upload_result));
	exit;
}
